const os = require('os');
const path = require('path');

USER_HOME = os.homedir();
GRADLE_HOME_DIRECTORY_NAME = '.gradle';
GRADLE_HOME_DIRECTORY_LOCATION = path.join(
    USER_HOME,
    GRADLE_HOME_DIRECTORY_NAME
);
GRADLE_PROPERTIES_FILE_NAME = 'gradle.properties';
GRADLE_PROPERTIES_FILE_LOCATION = path.join(
    GRADLE_HOME_DIRECTORY_LOCATION,
    GRADLE_PROPERTIES_FILE_NAME
);
GPM_HOME_DIRECTORY_NAME = '.gpm';
GPM_HOME_DIRECTORY_LOCATION = path.join(USER_HOME, GPM_HOME_DIRECTORY_NAME);
GPM_GLOBAL_PROPERTIES_FILE_NAME = 'global.properties';
GPM_DEFAULT_PROFILE_NAME = 'default';
GPM_CURRENT_PROFILE_FILE_MARKER = '.currentprofile';
PROPERTIES_FILE_EXTENSION = 'properties';

module.exports = {
    USER_HOME,
    GRADLE_HOME_DIRECTORY_NAME,
    GRADLE_HOME_DIRECTORY_LOCATION,
    GRADLE_PROPERTIES_FILE_NAME,
    GRADLE_PROPERTIES_FILE_LOCATION,
    GPM_HOME_DIRECTORY_NAME,
    GPM_HOME_DIRECTORY_LOCATION,
    GPM_GLOBAL_PROPERTIES_FILE_NAME,
    GPM_DEFAULT_PROFILE_NAME,
    GPM_CURRENT_PROFILE_FILE_MARKER,
    PROPERTIES_FILE_EXTENSION,
};
